# Generated by Django 5.2.4 on 2025-07-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="ім'я категорії")),
                ('img', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Час створення')),
                ('title', models.CharField(max_length=255, verbose_name="ім'я категорії")),
                ('price', models.FloatField()),
                ('watched', models.IntegerField(default=0, verbose_name='Перегляди')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість товару на складі')),
                ('desc', models.CharField(default='Тут скоро щось буде', verbose_name='Опис')),
                ('info', models.CharField(default='Додаткова інформація про продукт', verbose_name='Додаткова інформація')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('size', models.IntegerField(default=30, verbose_name='Розмір в мм')),
                ('color', models.CharField(default='Срібло', max_length=30, verbose_name='Матеріал/Колір')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Галерея картинок',
            },
        ),
    ]
