# Generated by Django 5.2.4 on 2025-07-23 14:49

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=shop.models.generate_random_slug, null=True, unique=True),
        ),
    ]
