# Generated by Django 5.2.4 on 2025-08-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_rating_alter_reviews_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
