# Generated by Django 5.2.4 on 2025-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customer_order_orderproduct_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
    ]
