# Generated by Django 5.2.4 on 2025-08-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
