# Generated by Django 5.2.4 on 2025-08-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_orderproduct_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name="ім'я категорії"),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name="ім'я категорії"),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_en',
            field=models.CharField(default='Тут скоро щось буде', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_uk',
            field=models.CharField(default='Тут скоро щось буде', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='info_en',
            field=models.CharField(default='Додаткова інформація про продукт', null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AddField(
            model_name='product',
            name='info_uk',
            field=models.CharField(default='Додаткова інформація про продукт', null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="ім'я категорії"),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name="ім'я категорії"),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст відгуку'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Текст відгуку'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=355, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=355, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(max_length=355, verbose_name='Вулиця'),
        ),
    ]
