# Generated by Django 5.2.4 on 2025-08-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_category_title_en_category_title_uk_product_desc_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='text_uk',
        ),
    ]
