# Generated by Django 5.2.4 on 2025-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
    ]
