# Generated by Django 5.2.4 on 2025-08-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_reviews_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
