# Generated by Django 5.2.4 on 2025-08-20 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_buyproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 20, 6, 0), verbose_name='Час створення'),
            preserve_default=False,
        ),
    ]
